branches:
  except:
    - gh-pages
language: perl6
sudo: true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y libsndfile1-dev
perl6:
  - latest
#  - 2015.09
install:
  - rakudobrew build-zef
  - zef --debug --depsonly install .
