name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: rakudo-star:latest

    steps:
    - uses: actions/checkout@v4

    - name: Raku version
      run: raku -v

    - name: Apt update
      run: apt-get update -qq

    - name: Install libsndfile
      run: apt-get install -y -qq libsndfile1-dev

    - name: Install dependencies
      run: zef install --deps-only --/test --test-depends .

    - name: Run tests
      run: zef test -v --debug .
